name: Run research
on:
  workflow_dispatch:
    inputs:
      company_name:
        description: "Company name"
        required: true
      company_url:
        description: "Company website (main domain)"
        required: true
      industries:
        description: "Comma-separated: Electrical engineering, Medical technology, Mechanical engineering"
        required: true
        default: "Electrical engineering, Medical technology, Mechanical engineering"
      region:
        description: "Region scope (e.g., DACH)"
        required: true
        default: "DACH"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run orchestrator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
          OPENCORPORATES_API_KEY: ${{ secrets.OPENCORPORATES_API_KEY }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          python run.py             --company-name "${{ github.event.inputs.company_name }}"             --company-url "${{ github.event.inputs.company_url }}"             --industries "${{ github.event.inputs.industries }}"             --region "${{ github.event.inputs.region }}"             --mode "full_auto"

      - name: Upload artifacts (CSV/JSON/PDF)
        uses: actions/upload-artifact@v4
        with:
          name: research_outputs
          path: |
            data/outputs/*.csv
            data/outputs/*.json
            data/outputs/*.pdf
